name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Build backend
        run: cd backend && npm install && npm run format && npm run compile

      - name: Build frontend
        run: cd frontend && npm install && npm run format && npm run compile
